### ISSUE TITLE
TypeError when resulting options have no HTML tags

### ISSUE THREAD

**Issue by ncuesta** [lndl/select2_simple_form#5]
When using this gem with an AJAX-fed select2 instance, if the `text` for a `result` doesn't contain any HTML tags, the regexp defined [here](https://github.com/lndl/select2_simple_form/blob/master/app/assets/javascripts/select2_simple_form/initializers.select2_simple_form.js#L48) in the custom matcher won't match the text, thus making the `.match()` call return a `null` value, and finally causing a TypeError to be thrown when `.index` is called on `null`.

**Comment by lndl** [comment]
Fixed in 0.7.2, @ncuesta. Thanks for reporting!
