### ISSUE TITLE
Could not find gem 'select2-simpleform' in any of the gem sources listed in your Gemfile.

### ISSUE THREAD

**Issue by Etienne-C** [lndl/select2_simple_form#6]
Hi,

Impossible to install the gem when I try to `bundle`,  have this message: 
`Could not find gem 'select2-simpleform' in any of the gem sources listed in your Gemfile.`

**Comment by lndl** [comment]
Hi @Etienne-C 
Select2-simpleform isn't hosted in RubyGems yet because some testing is missing. However, you still could install it specifying in your Gemfile:

```
gem 'select2_simple_form', github: 'lndl/select2_simple_form', tag: '0.7.3'
````
I've noticed that readme.md was wrong; thus, I corrected it. Thanks!
