### ISSUE TITLE
it's useless when clicked the element of searched result 

### ISSUE THREAD

**Issue by dwgeneral** [lndl/select2_simple_form#7]
I could get the right result set, but when I click any element of it, It's no any response

**Comment by lndl** [comment]
Hi!

Could you be more specific? What does it mean that there is no response?

**Comment by dwgeneral** [comment]
this is my searched result, when I clicked any one of them, it happened nothing, in other words, I couldn't set value for this select field

<img width="661" alt="screen shot 2017-06-19 at 9 42 20 pm" src="https://user-images.githubusercontent.com/8654993/27288563-b3938c0a-5539-11e7-8f3c-5b7fa907a04d.png">

**Comment by dwgeneral** [comment]
it's work ! the reason is my wrong returned json format from ajax. thanks !
